// reservas.routes.js
const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/reservas.controller');
const { autenticar, autorizar } = require('../middleware/auth.middleware');
router.use(autenticar);
router.get('/', ctrl.listar);
router.get('/agenda', ctrl.listarAgenda);
router.get('/bloqueos', autorizar('admin','recepcion','groomer'), ctrl.listarBloqueos);
router.post('/enviar-recordatorios', autorizar('admin','recepcion'), ctrl.enviarRecordatorios);
router.get('/historial', autorizar('admin','recepcion','cliente'), ctrl.historial);
router.post('/bloqueos', autorizar('admin','recepcion'), ctrl.crearBloqueo);
router.delete('/bloqueos/:id', autorizar('admin','recepcion'), ctrl.eliminarBloqueo);
router.get('/pagos', autorizar('admin','recepcion'), ctrl.listarPagos);
router.post('/pagos', autorizar('admin','recepcion','cliente'), ctrl.registrarPago);
router.patch('/pagos/:id/estado', autorizar('admin','recepcion'), ctrl.actualizarEstadoPago);
router.get('/:id', ctrl.obtener);
router.post('/', autorizar('admin','recepcion','cliente'), ctrl.crear);
router.patch('/:id/reprogramar', autorizar('admin','recepcion','cliente'), ctrl.reprogramar);
router.patch('/:id/cancelar', ctrl.cancelar);
router.patch('/:id/estado', autorizar('admin','recepcion','groomer'), ctrl.actualizarEstado);
module.exports = router;
